services:
  api:
    build: .
    container_name: express-learn-container
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  db:
    image: postgres:18
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: express_learn
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql 
      
volumes:
  postgres_data:  