import { PERMISSIONS } from "./permissions.js";

export const ROLE_PERMISSIONS = {
  admin: [
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,

    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.PRODUCT_DELETE,
  ],

  user: [PERMISSIONS.USER_READ, PERMISSIONS.PRODUCT_READ],
};
