import { PERMISSIONS } from "./permissions.js";

export const ROLE = {
  ADMIN: "admin",
  USER: "user",
};

export const ROLE_PERMISSIONS = {
  [ROLE.ADMIN]: [
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,

    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.PRODUCT_DELETE,
  ],

  [ROLE.USER]: [PERMISSIONS.USER_READ, PERMISSIONS.PRODUCT_READ],
};
